apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cm9vdA==       # root
  mysql-database: VFBQcm9qZXQ=        # TPProjet
  mysql-user: cm9vdA==                # root
  mysql-password: ""                  # vide
